Gustavo A. Aparicio V. - 20232005091

In [ ]:
# Crear un DataFrame

import pandas as pd # Se importa la biblioteca 'pandas' y se le asigna un nombre para facilitar su uso 'pd'

In [ ]:
numbers = [1, 2, 3, 4, 5, 6] # Se crea un arreglo de datos para usarlo en el DataFrame

In [ ]:
pd.DataFrame(numbers) # Se le asigna

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [ ]:
data = [["Jhon",  23], ["Mary", 18], ["Jhon", 31]] # 'data' es una Lista de Listas

In [ ]:
pd.DataFrame(data) # Dataframe donde la info son las listas de 'data'

      0   1
0  Jhon  23
1  Mary  18
2  Jhon  31

In [ ]:
pd.DataFrame(data, columns = ["name", "age"]) # Cambia el nombre de las columnas

   name  age
0  Jhon   23
1  Mary   18
2  Jhon   31

In [ ]:
pd.DataFrame(data, columns = ["name", "age"], index = ["id1", "id2", "id3"]) # Cambia el nombre del índice

     name  age
id1  Jhon   23
id2  Mary   18
id3  Jhon   31